name: 'Build cilium/cilium bpf programs'
inputs:
  output-dir:
    description: 'Path to the output of cilium build'
    required: true
  cilium-revision:
    description: 'Cilium revision to build. main is used by default'
    required: false

runs:
  using: "composite"
  steps:

    - name: Install cilium dependencies
      shell: bash
      run: ${GITHUB_ACTION_PATH}/install-dependencies.sh

    - name: Build cilium/cilium bpf programs
      env:
        OUTPUT_DIR: ${{ inputs.output-dir }}
        CILIUM_REVISION: ${{ inputs.cilium-revision }}
      shell: bash
      run: ${GITHUB_ACTION_PATH}/build-cilium.sh
